### ISSUE TITLE
Worker was destroyed

### ISSUE THREAD

**Issue by David-moonsite** [react-pdf-viewer/react-pdf-viewer#389] opened 2020-12-15 08:12 UTC
Hi ,
sometimes i get "Worker was destroyed",
why is it happening
![Screen Shot 2020-12-15 at 10 04 39](https://user-images.githubusercontent.com/58983212/102188502-085db780-3ebe-11eb-9ff1-464105b7774e.png)

**Comment by phuoc-ng** [comment] 2020-12-15 08:32
> sometimes

Can you let me know how to reproduce the issue?

**Comment by David-moonsite** [comment] 2020-12-15 08:59
- create list with 10 buttons 
- each button should open same modal with different Pdf Document
-  click on different button to open modal  and close it several times

**Comment by phuoc-ng** [comment] 2020-12-15 11:37
Where do you put the `Worker`?
It's recommended to put the `Worker` in the page, not in the modal.

**Comment by David-moonsite** [comment] 2020-12-15 11:39
In modal ,
i need to show pdf document in modal.

**Comment by phuoc-ng** [comment] 2020-12-15 11:45
You should put the `Worker` in the page. In the [Setting up the worker](https://react-pdf-viewer.dev/docs/basic-usage) section, it mentions that we should place the `Worker` at the root:

```js
const App = () => {
    return (
        <Worker
            workerUrl="https://unpkg.com/pdfjs-dist@2.5.207/build/pdf.worker.min.js"
        >
            ...
        </Worker>
    );
};

render(<App />, document.getElementById('root'));
```

**Comment by David-moonsite** [comment] 2020-12-15 12:00
OK,
i did it, same issue

**Comment by phuoc-ng** [comment] 2020-12-15 13:37
@phuoc-ng Found related issues
https://github.com/mozilla/pdf.js/issues/7057
https://github.com/mozilla/pdf.js/blob/master/test/unit/api_spec.js#L425

**Comment by WiemSoued** [comment] 2020-12-17 17:06
Same issue, even when the worker is placed at the root.
The message "Worker was destroyed" is shown then the pdf file is loaded.
Is there an explanation?

**Comment by WiemSoued** [comment] 2021-01-05 15:09
The issue is that the pdf.worker.min.js is called multiple times so the message "Worker was destroyed" is present while the pdf.worker.min.js is pending.
Is there any explanation for this behavior?

**Comment by WiemSoued** [comment] 2021-01-06 12:48
For anyone who needs this in the future,
 the issue is caused when you use multiple workers on the same page.
 If it's destroyed while still being initialized, you run into problems. The same happens if it's initialized while an earlier instance is still being destroyed.
I solved this by using a TimeOut.

**Comment by phuoc-ng** [comment] 2021-01-13 12:16
@David-moonsite 
@WiemSoued 
This issue is fixed in #424. I'll include the fix in v2.3.2!

_Reason_

By default, for each document pdf.js will create a web worker to parse and render the document.
The worker then will be reused if the it sees the same document.

Let's say that we have 3 documents, and there are 2 buttons, _Next_ and _Previous_ to load the previous and next document.
Initially, pdf.js will create a worker with id of `d_0` for the first document.

When user clicks the _Next_ button, it then destroys the `d_0` worker, and create a new worker, `d_1` to parse the second document.
If user clicks the _Previous_ button, it will reuse the `d_0` worker but the worker was destroyed.

In order to fix that, I create and destroy the worker manually.

**Comment by phuoc-ng** [comment] 2021-01-19 02:06
@David-moonsite 
@WiemSoued 
Please upgrade to [v2.3.2](https://react-pdf-viewer.dev/updates) which fixes the issue.

**Closed** 2021-01-19 02:06 UTC
Labels: question

**Comment by David-moonsite** [comment] 2021-01-19 08:42
Done, but now the top toolbar is gone ( download, zoom etc.... )
