### ISSUE TITLE
Loading a large pdf on Safari iOS and macOS causes a crash

### ISSUE THREAD

**Issue by esetnik** [react-pdf-viewer/react-pdf-viewer#490] opened 2021-03-15 15:14 UTC
```
[Warning] Total canvas memory use exceeds the maximum limit (384 MB). (2.c9af885f.chunk.js, line 2)
[Error] TypeError: null is not an object (evaluating 'r.canvasContext.canvas')
```

**Comment by esetnik** [comment] 2021-03-15 17:35
I believe this is related to https://github.com/mozilla/pdf.js/issues/11297 but I have no idea how to work around it.

**Comment by esetnik** [comment] 2021-04-13 00:56
@phuoc-ng still having this issue affecting over 1000 users across several different PDFs. The issue occurs on iOS and macOS safari approx. 1-1 ratio. Most common on newest versions of iOS and macOS safari. I've resorted to temporarily redirect safari  devices to download the pdfs instead of using embedded pdf viewer to avoid the issue but that's a bad workaround. 

Do you have any thing I should try?

**Comment by phuoc-ng** [comment] 2021-04-13 01:12
@esetnik I'll make this as one of top priorities.
Will see if I can provide some updates later.

**Comment by esetnik** [comment] 2021-04-17 14:38
@phuoc-ng any progress on this? Anything I can do to help debug further?

**Comment by phuoc-ng** [comment] 2021-04-18 14:50
@esetnik I tried the sample document in [this issue](https://github.com/mozilla/pdf.js/issues/11297#issue-515890020), but I couldn't reproduce the issue with my Safari 14.0.3, Chrome 90 macOS.

Here is the screenshot of the demo on Safari:

<img width="863" alt="Screen Shot 2021-04-18 at 21 47 00" src="https://user-images.githubusercontent.com/57786711/115149771-d046cb00-a08f-11eb-8b3e-4779a302eaa3.png">

Can you give me the sample document and steps to reproduce that on Safari?

**Comment by esetnik** [comment] 2021-04-20 16:43
@phuoc-ng it is easier to reproduce on mobile safari. Can you try iPhone or iPad?

**Comment by phuoc-ng** [comment] 2021-04-25 05:56
@esetnik 
I can view the document on Safari iPhone, but couldn't reproduce the issue. Maybe the document isn't big enough.
Can you give me the sample document?

**Comment by FeiHsiang** [comment] 2021-05-03 10:14
Hi, I found the actual solution to work around this problem.
First, I am working with pdfjsLib version 2.0.943, simply   
`pdfjsLib.getDocument(...).then((pdf)=>{...})` then `pdf.getPage(i).then(page)`

Then 
```
let pdfCanvas = document.createElement('canvas');
let ctx = pdfCanvas.getContext('2d');
page.render({
    canvasContext: ctx,
}); 
```

Run the upper part on ios safari with about 634kB( 120 pages ), and the canvas(1200x1500). 
Refresh the page about three times will casue the following warning.

**Total canvas memory use exceeds the maximum limit**

and the canvas only show the blank page.

Add the following code will release the memory 
```
window.onunload = function(){
    let canvases = document.getElementsByTagName("canvas");
    while( canvases[0] ){
        canvases[0].width = 0;
        canvases[0].height = 0;
        canvases[0].remove();
    }
}
```
Finally I can get the correct page content no matter how many times refresh.

Note:
If the pdf file with huge number of page, I dont think it will work.
Do not use `window.onbeforeunload`, because the ios refresh won't trigger this event.

Sorry for my poor English.

**Comment by phuoc-ng** [comment] 2021-05-08 12:16
Updated: I can reproduce the issue on iOS with the following steps:
* Zoom the document to big enough level, 150% for example
* Scroll down from page 1

If the document is big, we will soon see the error

<img width="1498" alt="Screen Shot 2021-05-08 at 18 36 17" src="https://user-images.githubusercontent.com/57786711/117538802-e06c1d80-b031-11eb-92d5-4e66e5759fd5.png">

**Comment by FeiHsiang** [comment] 2021-05-10 01:26
Hi phuoc-ng, 
I try an other way to show the pdf page. Instead of canvas, I generate a png from the canvas and remove the canvas immediately.

```
let pageContainer = document.createElement('div');
let pdfCanvas = document.createElement('canvas');

pageContainer.appendChild(pdfCanvas);
pdfDiv.appendChild(pageContainer); //// in dom

let ctx = pdfCanvas.getContext('2d');
var viewport = page.getViewport( scaleRatio );

let task = page.render({
    canvasContext: ctx,
    viewport: viewport,
});

task.promise.then(function(e){
    let dataURL = pdfCanvas.toDataURL();
    pageContainer.style.backgroundImage = "url(" + dataURL + ")";

    pdfCanvas.width = 0;
    pdfCanvas.height = 0;
    pdfCanvas.remove();
    
});

```
It is work for me. If you apply the lager PDF, I will try later.

**Comment by esetnik** [comment] 2021-06-07 17:47
@phuoc-ng any update on this?

**Comment by FredZeng** [comment] 2021-10-21 02:52
1. Resuing Canvas by introducing a Canvas Pool. (only render visible pages)
2. Reset PDFDocument's cache to reduce memory usage.

**Comment by visuallization** [comment] 2021-11-29 12:37
I experienced the same issue on an Iphone 8 Plus with a relatively small Pdf (192 KB). Once I zoomed into 150% and started to scroll it would crash with the following error message. That's actually a blocker.

@phuoc-ng Did you find a way to fix this or work around it?

![Image-2021-11-29 13_28_32](https://user-images.githubusercontent.com/6199277/143869249-55f3baaa-980e-415a-90d3-19b6d7ceb795.png)

**Comment by visuallization** [comment] 2021-12-01 13:51
This is also happening on https://react-pdf-viewer.dev/ if you zoom and scroll the provided pdf on Safari on an Iphone.

![IMG_0253](https://user-images.githubusercontent.com/6199277/144246288-141b93f9-8445-4603-8d02-7158bede2ce3.PNG)
<img width="1624" alt="Screenshot at Dec 01 14-22-48" src="https://user-images.githubusercontent.com/6199277/144245935-9243382c-4fb5-4bc0-bdcf-4fa0178f6881.png">

**Comment by visuallization** [comment] 2021-12-01 13:57
Interesting thing is that it works really well on the Iphone with the demo mozilla has provided: https://mozilla.github.io/pdf.js/legacy/web/viewer.html

So there are some settings and/or implementations we might need to add to react-pdf-viewer.

**Comment by visuallization** [comment] 2021-12-13 13:50
@phuoc-ng do you have updates or ideas on this. As already mentioned above, this also happens for small pdfs (192kb). We have plenty of iphone users and a crash/whitescreen is unfortunately a blocker for us.

**Comment by phuoc-ng** [comment] 2021-12-13 15:30
This is my highest priority after v3.0.0!

**Comment by visuallization** [comment] 2021-12-15 10:47
@phuoc-ng awesome, that's great to hear!

**Comment by phuoc-ng** [comment] 2022-01-16 14:10
@esetnik @denisLoncaric @visuallization @FeiHsiang @FredZeng
This was implemented in the latest code, and will be included in the next v3.1.0.
The viewer works on mobile without any crashes!

**Comment by visuallization** [comment] 2022-01-16 17:06
@phuoc-ng sounds great! Looking forward to the fix!

**Comment by phuoc-ng** [comment] 2022-01-20 15:43
@esetnik @denisLoncaric @visuallization @FeiHsiang @FredZeng
[v3.1.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade!

**Closed by phuoc-ng** 2022-01-20 15:43 UTC
Labels: bug, core

**Comment by Ali-X** [comment] 2023-04-27 10:18
@phuocng 
The bug is still reproduced!

Version 3.12.0
iOS 16.3.1

**Comment by Dave-Lopper** [comment] 2023-05-09 06:48
I am also encountering the issue on v3.12.0 on various IoS versions and devices
