### ISSUE TITLE
disabling shortcuts on page navigation not working.

### ISSUE THREAD

**Issue by kdv24** [react-pdf-viewer/react-pdf-viewer#1194] opened 2022-07-07 19:51 UTC
```
const pageNavigationPluginInstance = pageNavigationPlugin({
    enableShortcuts: false
});
  ```

I'm trying to disable the pageNavigation in certain situations, but using the above code, I'm unable to disable it at any time. Shouldn't this alone set the arrow shortcuts to be disabled?

**Comment by phuoc-ng** [comment] 2022-07-31 03:02
@kdv24 The issue is fixed in the latest code, and will be included in the next release.
The actual issue is that we can't set the `enableShortcuts` option when using the default layout plugin:

```js
const defaultLayoutPluginInstance = defaultLayoutPlugin({
    toolbarPlugin: {
        pageNavigationPlugin: {
            enableShortcuts: true,
        },
    },
});
```

It's worth noting that even if you set `enableShortcuts: false`, the content will scroll down/up when users pressing `PageDown`, `PageUp` keys.
It's the default behavior of the browser, and we don't prevent that.

**Comment by phuocng** [comment] 2022-09-04 02:14
Done.

**Closed by phuocng** 2022-09-04 02:14 UTC
Labels: page-navigation plugin
