### ISSUE TITLE
onPageChange does not trigger if currentPage = initialPage

### ISSUE THREAD

**Issue by frdwhite24** [react-pdf-viewer/react-pdf-viewer#1197] opened 2022-07-11 18:42 UTC
Thanks for the great work!

## Description

`onPageChange` does not get triggered if the `currentPage` is equal to the `initialPage`, and I found [this condition](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/6ceb7976a039fae0146c0b0e871bb018a5372482/packages/core/src/layouts/Inner.tsx#L394) which explains why it doesn't, my question is why is this the case?

## Steps to replicate:

- Follow basic getting started guide in docs
- Add a simple callback to the `onPageChange` prop of the `Viewer`: `(e) => console.log(e)`
- To make it clear, add `initialPage` as `5`, but this works with no `initialPage` too, it just defaults to 0
- Scroll through the document, passing over page index 5 (or page index 0 if you didn't pass in `initialPage`)

## Actual behaviour

No `PageChangeEvent` is logged to the console when you pass over the initial page

## Expected behaviour

A `PageChangeEvent` is logged to the console every time a page is changed, regardless of if it is the initial page or not

## My use case
I have outside state storing the current page value so I can show it on the UI outside of the PDF viewer component. I also have a specific initial page to load as the PDFs we're dealing with are often very large, and so it saves time loading just the page I need, rather than always waiting for the 1st page to load first. As such, I passed in the `initialPage` prop to the Viewer. The `onPageChange` handler increments my outside state value to the current visible page.

Let me know if you would like me to replicate it in a simple example. As I was able to track it to a specific line in the source, I'll consider this more a question than a bug, until you can confirm that this is not intended behaviour.

**Comment by frdwhite24** [comment] 2022-08-06 22:03
hi @phuocng, do you have an update on this? Do you see it as something that you'd accept changing? i'm happy to fork and open a PR if you'll accept the removal of the condition I have linked above, I'm just not sure of the wider knock on impact of it

**Comment by SivaNithish** [comment] 2022-08-08 07:41
Oh THANKS ! I found this error too, glad that i'm not the only one. Did you found a fix to it @frdwhite24 ? Or an alternative to get the current page number even if it's the initial page ?

**Comment by SivaNithish** [comment] 2022-08-12 09:46
@frdwhite24 Thanks for your reply, i see but dont worry ! I'll try to find an alternative to it too.

**Comment by phuocng** [comment] 2022-08-16 15:43
@frdwhite24 @SivaNithish 
Update: The issue is fixed in the latest code, and will be included in the next v3.7.0.

**Comment by frdwhite24** [comment] 2022-08-22 08:39
I've just upgraded to v3.7.0 and I can confirm that the bug is resolved! thank you for including this in the latest release @phuocng, feel free to close the issue if you are also satisfied

**Comment by phuocng** [comment] 2022-09-04 02:15
Released in [v3.7.0](https://react-pdf-viewer.dev/updates/).

**Closed by phuocng** 2022-09-04 02:15 UTC
Labels: bug, core
