### ISSUE TITLE
Safari 14: Default toolbar buttons don't get pointer events

### ISSUE THREAD

**Issue by martinschilliger** [react-pdf-viewer/react-pdf-viewer#477] opened 2021-03-05 05:59 UTC
It's a bit hard to describe, thats why I've made a small video. It happens with the default implementation of the toolbar on [the website](https://react-pdf-viewer.dev), but not for example with the floating toolbar. In latest Firefox and Chrome everything works as expected.

https://user-images.githubusercontent.com/11884891/110073548-d7d04000-7d7f-11eb-8150-11d956d33502.mov

**Comment by phuoc-ng** [comment] 2021-03-07 14:58
Thanks for reporting the issue, @martinschilliger.
It's caused by the _Open file_ button. (You can open the developer tools on Safari, and remove the _Open file_ button. And the other buttons will work fine).

I'll let you know when the issue gets fixed.

**Comment by phuoc-ng** [comment] 2021-03-07 15:21
The issue was fixed in the latest code.

_Demo_

https://user-images.githubusercontent.com/57786711/110244880-6963cb80-7f93-11eb-8d06-8707bb6b9b4a.mp4

**Comment by phuoc-ng** [comment] 2021-03-07 15:23
If you're curious about the root cause, then here it is. On Safari, the Open button (which is a customized file input) covers other elements.

In the following screenshot, the actual input is indicated by a yellow area:

<img width="925" alt="Screen Shot 2021-03-07 at 22 13 53" src="https://user-images.githubusercontent.com/57786711/110244914-93b58900-7f93-11eb-8f64-fd74319ad397.png">

**Comment by phuoc-ng** [comment] 2021-03-07 15:44
@martinschilliger v2.4.1 was [released](https://react-pdf-viewer.dev/updates). Please update.

**Closed by phuoc-ng** 2021-03-07 15:44 UTC
Labels: bug, open plugin, toolbar plugin

**Comment by martinschilliger** [comment] 2021-03-09 10:21
Wow, that was crazy fast! Thank you!
