### ISSUE TITLE
Clicking first bookmarks item bug

### ISSUE THREAD

**Issue by makranelhoucine** [react-pdf-viewer/react-pdf-viewer#1224] opened 2022-08-09 16:39 UTC
Hello 

Clicking on first bookmarks item freezes pdfviewer and browser tab

I must close the current tab and open new one

FYI: Clicking other bookmarks doesn't cause this issue

I tried v3.3.2 and the last v3.6.0

**Comment by phuocng** [comment] 2022-08-10 01:26
@makranelhoucine The issue is the same as #1218
It is fixed in the latest code, and will be included in the next release.

**Comment by makranelhoucine** [comment] 2022-08-10 07:42
> @makranelhoucine The issue is the same as #1218 It is fixed in the latest code, and will be included in the next release.


Thank you

**Comment by phuocng** [comment] 2022-09-04 02:15
Released in [v3.7.0](https://react-pdf-viewer.dev/updates/).

**Closed by phuocng** 2022-09-04 02:15 UTC
Labels: bug, core
