### ISSUE TITLE
Bug on search next result

### ISSUE THREAD

**Issue by iOrchK** [react-pdf-viewer/react-pdf-viewer#585] opened 2021-06-05 00:36 UTC
![image](https://user-images.githubusercontent.com/38798286/120874404-1be40400-c56c-11eb-9ad2-9a89c173ff95.png)

**Comment by phuoc-ng** [comment] 2021-06-05 01:11
Can I reproduce the issue with the [live website](https://react-pdf-viewer.dev/)?
If not, may I look at the document? (You can share it to my email).

**Comment by iOrchK** [comment] 2021-06-05 03:40
No, it's in a next.js project, I only copy this code in my project component and the I try the search, write a text and then click on the arrow down of the search window
![image](https://user-images.githubusercontent.com/38798286/120879007-e51ae780-c585-11eb-999f-361e9fa74f3b.png)

**Comment by phuoc-ng** [comment] 2021-06-05 03:43
I can't help you if I can't reproduce the issue.
I think the issue is caused by a specific document, not all document. Being able to reproduce the issue is important, it will fix the root cause.

The [official website](https://react-pdf-viewer.dev/) is powered by NextJS as well.

**Comment by iOrchK** [comment] 2021-06-05 03:49
Ok this is my component PDFViewer.js, you can import this in an App.js, I pass this pdf (https://notaria230.blob.core.windows.net/documentos/prueba pdf_1622778653.pdf) as base64 because the viewer can't open it. 
`
import React from "react";
import { LocalizationProvider, Viewer, Worker } from "@react-pdf-viewer/core";
import { defaultLayoutPlugin } from "@react-pdf-viewer/default-layout";
import "@react-pdf-viewer/core/lib/styles/index.css";
import "@react-pdf-viewer/default-layout/lib/styles/index.css";
import es_MX from "./es_MX.json";

const PDFViewer = ({ fileUrl }) => {
  // Create new plugin instance
  const defaultLayoutPluginInstance = defaultLayoutPlugin();

  if (!fileUrl) return null;

  return (
    <Worker workerUrl="https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js">
      <LocalizationProvider localization={es_MX}>
        <Viewer fileUrl={fileUrl} plugins={[defaultLayoutPluginInstance]} />
      </LocalizationProvider>
    </Worker>
  );
};

export default PDFViewer;
`

**Comment by iOrchK** [comment] 2021-06-05 03:57
https://user-images.githubusercontent.com/38798286/120879335-3b892580-c588-11eb-93ff-1b5ba649047b.mp4

**Comment by phuoc-ng** [comment] 2021-06-06 07:11
@iOrchK 
The issue was fixed in the latest code. It will be included in the next v2.6.0.

**Comment by iOrchK** [comment] 2021-06-07 19:57
Ok, thanks

**Comment by phuoc-ng** [comment] 2021-06-22 13:58
@iOrchK [v2.6.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade if you already purchase.

**Closed by phuoc-ng** 2021-06-22 13:58 UTC
Labels: bug, search plugin
