### ISSUE TITLE
Page resizing scrolls to initialPage

### ISSUE THREAD

**Issue by frdwhite24** [react-pdf-viewer/react-pdf-viewer#1435] opened 2023-02-22 14:09 UTC
Thanks again for the great work, and for addressing our previous bug.

**Description:**
If the page is resized (i.e. going from full screen to split screen with your browser), and you have provided the `Viewer` with an `initialPage` prop, it'll scroll to this page, wherever you are when you resized the browser rather than maintaining your current page.

**Steps to replicate:**

- Follow basic getting started guide in docs
- Add initialPage as 5
- Scroll elsewhere in the document
- Resize the browser window (go split screen, or change the width of the console etc)

**Actual behaviour:**
The PDF scrolls to whatever was provided as the initial page.

**Expected behaviour:**
The PDF resizes and maintains the current viewed page.

**My use case:**
I have just made a sidebar for our application which renders content next to the PDF viewer. Users can expand/collapse the sidebar. Whenever the user does this, it triggers this scroll behaviour even if nothing else has changed. Can imagine it will get very annoying for the users to have their page reset even if they haven't touched the PDF! Appreciate the time you spend looking into this. I'll investigate a bit too.

**Comment by phuocng** [comment] 2023-02-26 12:08
@frdwhite24 Thanks for reporting the issue.
The issue is actually fixed in the latest code, and I will include it in the next release (v3.12.0).

## Demo

https://user-images.githubusercontent.com/57786711/221409534-6a70a76f-3487-45fa-b82a-5b6ea39badea.mp4

**Comment by frdwhite24** [comment] 2023-02-26 20:29
Thanks so much @phuocng !! Looked through the PR and the approach seems sensible 😊 do you anticipate doing the release for the end of Feb or is it planned for later?

**Comment by viktorlarsson** [comment] 2023-03-15 14:35
This would be great to get released!

**Closed** 2023-03-27 14:34 UTC
Labels: bug, core
